In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "/Users/llouis/Desktop/LLouis/AI_Everything/1. 기초 수학 및 프로그래밍/1. 수학 기초/1. 선형대수학/11. 선형대수 적용/forestfires.csv")

In [3]:
df.head()

X  Y  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

## 6번째 열 추출

In [4]:
df.iloc[:, 5]

0       5.1
1       6.7
2       6.7
3       9.0
4       9.6
       ... 
512     1.9
513     1.9
514     1.9
515    11.3
516     1.1
Name: ISI, Length: 517, dtype: float64

In [5]:
df['ISI']

0       5.1
1       6.7
2       6.7
3       9.0
4       9.6
       ... 
512     1.9
513     1.9
514     1.9
515    11.3
516     1.1
Name: ISI, Length: 517, dtype: float64

## 7번째 열 추출

In [6]:
df.iloc[:, 6]

0       8.2
1      18.0
2      14.6
3       8.3
4      11.4
       ... 
512    27.8
513    21.9
514    21.2
515    25.6
516    11.8
Name: temp, Length: 517, dtype: float64

In [7]:
df['temp']

0       8.2
1      18.0
2      14.6
3       8.3
4      11.4
       ... 
512    27.8
513    21.9
514    21.2
515    25.6
516    11.8
Name: temp, Length: 517, dtype: float64

## 6번째 열 + 7번째 열

In [8]:
ISI = df['ISI']
temp = df['temp']

In [9]:
ISI + temp

0      13.3
1      24.7
2      21.3
3      17.3
4      21.0
       ... 
512    29.7
513    23.8
514    23.1
515    36.9
516    12.9
Length: 517, dtype: float64

# 6번째 열, 7번째 열 내적

In [10]:
import numpy as np

ISI.dot(temp)

np.float64(93489.29000000001)

## 전치행렬 구하기

In [11]:
import numpy as np

df_t = np.transpose(df)

In [12]:
df_t

0      1      2     3      4      5      6      7      8      9    ...  \
X      7.0    7.0    7.0   8.0    8.0    8.0    8.0    8.0    8.0    7.0  ...   
Y      5.0    4.0    4.0   6.0    6.0    6.0    6.0    6.0    6.0    5.0  ...   
FFMC  86.2   90.6   90.6  91.7   89.3   92.3   92.3   91.5   91.0   92.5  ...   
DMC   26.2   35.4   43.7  33.3   51.3   85.3   88.9  145.4  129.5   88.0  ...   
DC    94.3  669.1  686.9  77.5  102.2  488.0  495.6  608.2  692.6  698.6  ...   
ISI    5.1    6.7    6.7   9.0    9.6   14.7    8.5   10.7    7.0    7.1  ...   
temp   8.2   18.0   14.6   8.3   11.4   22.2   24.1    8.0   13.1   22.8  ...   
RH    51.0   33.0   33.0  97.0   99.0   29.0   27.0   86.0   63.0   40.0  ...   
wind   6.7    0.9    1.3   4.0    1.8    5.4    3.1    2.2    5.4    4.0  ...   
rain   0.0    0.0    0.0   0.2    0.0    0.0    0.0    0.0    0.0    0.0  ...   
area   0.0    0.0    0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

        507    508     509     510    511     512     513     514    515  \
X       2.0    1.0    5.00    6.00    8.0    4.00    2.00    7.00    1.0   
Y       4.0    2.0    4.00    5.00    6.0    3.00    4.00    4.00    4.0   
FFMC   91.0   91.0   91.00   91.00   81.6   81.60   81.60   81.60   94.4   
DMC   166.9  166.9  166.90  166.90   56.7   56.70   56.70   56.70  146.0   
DC    752.6  752.6  752.60  752.60  665.6  665.60  665.60  665.60  614.7   
ISI     7.1    7.1    7.10    7.10    1.9    1.90    1.90    1.90   11.3   
temp   25.9   25.9   21.10   18.20   27.8   27.80   21.90   21.20   25.6   
RH     41.0   41.0   71.00   62.00   35.0   32.00   71.00   70.00   42.0   
wind    3.6    3.6    7.60    5.40    2.7    2.70    5.80    6.70    4.0   
rain    0.0    0.0    1.40    0.00    0.0    0.00    0.00    0.00    0.0   
area    0.0    0.0    2.17    0.43    0.0    6.44   54.29   11.16    0.0   

        516  
X       6.0  
Y       3.0  
FFMC   79.5  
DMC     3.0  
DC    106.7  
ISI     1.1  
temp   11.8  
RH     31.0  
wind    4.5  
rain    0.0  
area    0.0  

[11 rows x 517 columns]

In [13]:
df.shape

(517, 11)

In [14]:
df_t.shape

(11, 517)

# 피처/타겟 데이터 분할

In [15]:
feature = ['X', 'Y', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind', 'rain']
X = df[feature]
y = df['area']

In [16]:
X

X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain
0    7  5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0
1    7  4  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0
2    7  4  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0
3    8  6  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2
4    8  6  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...
512  4  3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0
513  2  4  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0
514  7  4  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0
515  1  4  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0
516  6  3  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0

[517 rows x 10 columns]

In [17]:
y

0       0.00
1       0.00
2       0.00
3       0.00
4       0.00
       ...  
512     6.44
513    54.29
514    11.16
515     0.00
516     0.00
Name: area, Length: 517, dtype: float64

## 공분산 행렬 구하기

In [19]:
import numpy as np

Xt = np.transpose(X)
cov_X = np.cov(Xt)

In [20]:
cov_X

array([[ 5.35356784e+00,  1.53540102e+00, -2.68720106e-01,
        -7.17001897e+00, -4.93132818e+01,  6.55124976e-02,
        -6.88667101e-01,  3.21760155e+00,  7.79260942e-02,
         4.47760635e-02],
       [ 1.53540102e+00,  1.51265500e+00, -3.14390566e-01,
         6.12959756e-01, -3.08690039e+01, -1.37321383e-01,
        -1.72133882e-01,  1.24869926e+00, -4.48221702e-02,
         1.20972216e-02],
       [-2.68720106e-01, -3.14390566e-01,  3.04716238e+01,
         1.35272459e+02,  4.52587277e+02,  1.33849023e+01,
         1.38319965e+01, -2.71119330e+01, -2.81718209e-01,
         9.26348342e-02],
       [-7.17001897e+00,  6.12959756e-01,  1.35272459e+02,
         4.10195189e+03,  1.08385013e+04,  8.91029647e+01,
         1.74639099e+02,  7.71213591e+01, -1.20879231e+01,
         1.41765463e+00],
       [-4.93132818e+01, -3.08690039e+01,  4.52587277e+02,
         1.08385013e+04,  6.15368355e+04,  2.59185313e+02,
         7.14751694e+02, -1.58640438e+02, -9.04300084e+01,
         2.

In [21]:
cov_X.shape

(10, 10)

## 공분산 행렬이 대칭 행렬인지 확인

In [22]:
cov_Xt = np.transpose(cov_X)

In [23]:
np.array_equal(cov_X, cov_Xt)

True

## 특이값 분해

In [24]:
import numpy as np

U, S, Vt = np.linalg.svd(cov_X)

In [25]:
U

array([[-7.84161966e-04, -9.27379422e-04,  1.08658320e-02,
        -2.63645372e-02,  3.52332542e-02, -3.65886924e-02,
        -9.42981440e-01, -1.69298160e-02,  3.27187594e-01,
        -7.27452344e-03],
       [-4.76391370e-04, -2.90688105e-03,  3.13357839e-03,
         2.44925122e-03,  2.20954020e-02, -2.14500189e-02,
        -3.26540197e-01,  3.16837402e-02, -9.44135810e-01,
         1.55168445e-03],
       [ 7.39788693e-03, -2.40648773e-02, -1.20638390e-01,
        -7.35224863e-01, -4.79913793e-01, -4.61483637e-01,
         1.63414022e-02, -2.45747489e-02, -9.46634830e-03,
        -3.45915203e-03],
       [ 1.79460941e-01, -9.81553201e-01, -4.36605345e-02,
         4.38094859e-02, -1.76489666e-02,  1.37466645e-02,
        -1.22576354e-03,  3.49614055e-03,  2.71636640e-03,
         1.04827539e-04],
       [ 9.83655890e-01,  1.79440679e-01,  1.37191816e-02,
         2.07028340e-03, -3.78024397e-03,  3.47075372e-03,
        -1.40101029e-03, -9.06791209e-04, -7.11010526e-04,
         5.

In [26]:
S

array([6.35277296e+04, 2.13335626e+03, 2.74882457e+02, 3.01009922e+01,
       1.46476605e+01, 9.91077255e+00, 5.76371012e+00, 2.76170396e+00,
       9.51625281e-01, 8.35607679e-02])

In [27]:
Vt

array([[-7.84161966e-04, -4.76391370e-04,  7.39788693e-03,
         1.79460941e-01,  9.83655890e-01,  4.27009270e-03,
         1.15707684e-02, -2.26100024e-03, -1.43490489e-03,
         4.47911510e-05],
       [-9.27379422e-04, -2.90688105e-03, -2.40648773e-02,
        -9.81553201e-01,  1.79440679e-01, -1.93781450e-02,
        -1.95041695e-02, -5.48221278e-02, -2.08301747e-03,
        -4.46240649e-04],
       [ 1.08658320e-02,  3.13357839e-03, -1.20638390e-01,
        -4.36605345e-02,  1.37191816e-02, -5.35283391e-02,
        -2.01160835e-01,  9.69459104e-01,  6.32273979e-03,
         1.46248864e-03],
       [-2.63645372e-02,  2.44925122e-03, -7.35224863e-01,
         4.38094859e-02,  2.07028340e-03, -6.25991140e-01,
        -1.92315397e-01, -1.63493151e-01, -3.47936034e-02,
        -5.38810667e-03],
       [ 3.52332542e-02,  2.20954020e-02, -4.79913793e-01,
        -1.76489666e-02, -3.78024397e-03,  2.80704097e-01,
         8.17936186e-01,  1.24704007e-01, -6.48935986e-02,
         7.

# 머신러닝 적용

In [28]:
# 트레이닝/테스트 데이터 분할
from sklearn.model_selection import train_test_split

X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state=0)

In [29]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler

std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [30]:
# KNN 회귀분석 학습
from sklearn.neighbors import KNeighborsRegressor

clf_knn = KNeighborsRegressor(n_neighbors=5)
clf_knn.fit(X_tn_std, y_tn)

KNeighborsRegressor()

In [31]:
# 예측
pred_y = clf_knn.predict(X_te_std)

In [32]:
pred_y

array([9.20800e+00, 1.84600e+00, 1.64340e+01, 1.88200e+00, 7.12400e+00,
       4.40800e+00, 1.27320e+01, 9.36400e+00, 8.96400e+00, 1.16320e+01,
       3.23000e+00, 1.26240e+01, 1.89200e+00, 1.25740e+01, 2.21200e+00,
       9.53400e+00, 2.27460e+01, 1.27200e+00, 1.27600e+00, 5.18600e+00,
       1.20920e+01, 3.62000e+00, 7.33800e+00, 4.26420e+01, 3.64860e+01,
       1.79200e+00, 9.48000e-01, 2.51800e+00, 5.19000e+00, 2.09940e+01,
       9.27000e+00, 4.47200e+00, 1.11600e+00, 1.67280e+02, 1.49550e+02,
       1.68980e+01, 0.00000e+00, 2.17600e+00, 2.06200e+00, 1.66726e+02,
       6.06400e+00, 7.79400e+00, 1.17640e+01, 6.91000e+00, 7.67000e+00,
       1.25800e+01, 1.08000e+00, 1.49400e+00, 4.25760e+01, 2.13260e+01,
       1.11240e+01, 2.09940e+01, 7.51600e+00, 0.00000e+00, 1.07000e+00,
       0.00000e+00, 2.87000e+00, 3.77000e+00, 2.24800e+00, 8.14200e+00,
       1.04840e+01, 1.77000e+00, 2.60500e+01, 2.86400e+00, 1.20920e+01,
       4.26420e+01, 3.40800e+01, 2.22040e+01, 1.78200e+00, 1.132

In [33]:
# 모형 평가-MSE
from sklearn.metrics import mean_squared_error

print(mean_squared_error(y_te, pred_y))

10710.621275692307
